### PR TITLE
Modify regex split

### LINKED ISSUE #33: How to deal with 'mean' in a variable name
If for example, someone wants:

` experiment::ObsValue::${variable}-experiment::hofx_y_mean_xb0::${variable}`

like from the output from the ensemble application(s), eva will fail.

It finds 'mean' and tries to separate it out, even though it is part of the variable name. Can we 'escape' a keyword in the variable name somehow?

Thanks to @weihuang-jedi for finding this.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Closes #33 

This removes `mean`, `sqrt`, and `\d` from the `regex.split` command for the arithmetic.

Currently, if a variable/group/collection contains a number or 'mean' or 'sqrt' in its name, it will fail. This should fix that. However, we will still need a solution eventually for dealing with 'functions' (mean, sqrt, others)

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
There's some bizarre stuff going on with the CI attempting to install cartopy... which is an old version because of an old version of 'proj'. I think we probably need to get new 'proj' compiled/installed in the CI and use a newer cartopy. I have to go to meetings but can investigate later today.

**Comment by CoryMartin-NOAA** [comment]
@danholdaway since we don't have unit tests, should the CI that checks coding norms just do that and not install dependencies?

**Comment by danholdaway** [comment]
Yeah that would likely make sense for now. Just turn off all this install. And then we wont have to have this strange dependency on a fixed version.

**Review by danholdaway — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
@danholdaway well I found a fix for the short term that keeps things as-is

**Pull request merged**
