### PR TITLE
Start to add very generic plotting controlled through YAML

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

This is a start to controlling figure generation 100% through YAML. Would like some initial comments on design. 

The tests/config/testDummy.yaml creates a figure like so:
Screen Shot 2022-03-07 at 2 23 00 PM

### CODE REVIEW

**Review by kevindougherty-noaa — COMMENTED** [review]
My first initial go through, I like the concept of everything being in a yaml. It's straight forward and you do not need Python experience to utilize this. It will be easy to translate into subplots if necessary and has everything in one spot neatly. However, there will definitely need to be lots of documentation for users on how to include other inputs for features i.e fontsize/fontweight for titles and labels etc.

One thing I'm not quite sure I understand is the data aspect. Will the user be responsible for getting the arrays in order to plot? Do they have to create their own python script? I see `dummy.py` but I'm not sure I entirely understand how that will translate with real data.

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa the idea is that the first part of the YAML would specify what data would be collected and stored in a dataframe to then be plotted by the second part of the yaml, see https://github.com/danholdaway/eva/blob/feature/plot_schema/src/eva/tests/config/ObsCorrelationScatterDriver.yaml for Dan and I's brainstorming doc (the first part)

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA I see, that makes sense. There would be a script within this repository that handles grabbing that input and returning the appropriate data?

**Comment by CoryMartin-NOAA** [comment]
yeah the dummy.py Dummy class handles that for now, but a more comprehensive class might be IodaObsSpace or GsiDiag or FV3ModelState for example.

**Comment by danholdaway** [comment]
Looks good to me @CoryMartin-NOAA. I like the design of splitting the creator in base into the data then graphics. It makes a lot of sense. I agree @kevindougherty-noaa that we will need careful documentation. Perhaps we should have a bit of a think about how to document the default Yamls. Probably we need to put lots of info in the docs but making sure we have a system in place to ensure docs updated might be tricky. Once we have this new structure finalized we should do some kind of documentation sprint

**Comment by CoryMartin-NOAA** [comment]
@danholdaway yeah one approach is to have comments for each entry in the default YAML, but is that the best approach? For example, default might not be 'all options'. So it would be good to have a place where all options are listed (and what the defaults are)

**Comment by CoryMartin-NOAA** [comment]
@danholdaway marked ready to review to PR into the develop-reorg branch so that any further changes I make can be minor (and allow you to more easily add the data I/O stuff)

**Review by danholdaway — APPROVED** [review]

**Pull request merged**
