### PR TITLE
Update ioda_obs_space.py

### PR DESCRIPTION
**Pull request by ADCollard**
Coding norms, plus change Channel_Number to channelNumber

## Description

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of what this PR does.

What problem does it fix? What new capability does it add?

## Dependencies

If there are PRs that need to be merged before or along with this one, please list them below
Waiting on the following PRs:
- [ ] waiting on org/repo/pull/<pr_number>
- [ ] waiting on org/repo/pull/<pr_number>

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] repo
- [ ] ...

### CODE REVIEW

**Comment by ADCollard** [comment]
@CoryMartin-NOAA Apparently I cannot merge into my own branch because it is protected.  Also Emily does appear to have access to this repository (at least I cannot tag her to review).

**Comment by CoryMartin-NOAA** [comment]
@ADCollard I'm not sure if that's the reason or if it is because the automated tests are failing.

**Comment by CoryMartin-NOAA** [comment]
@ADCollard why not just push this commit to the existing branch/PR? and I don't have permissions to add her/others to the repo, we have to go through JCSDA for that.

**Comment by ADCollard** [comment]
> @ADCollard why not just push this commit to the existing branch/PR? and I don't have permissions to add her/others to the repo, we have to go through JCSDA for that.

It wasn't letting me do that.  I am sorry, I forgot you did not have authority over this repository.

```
(eva) Hera(hfe06):/scratch1/NCEPDEV/da/Andrew.Collard/git/eva/src/eva/data$ git commit -a -m "Coding norms and change Channel_Number to channelNumber"
[andrew 7db7016] Coding norms and change Channel_Number to channelNumber
 1 file changed, 2 insertions(+), 3 deletions(-)
(eva) Hera(hfe06):/scratch1/NCEPDEV/da/Andrew.Collard/git/eva/src/eva/data$ git push origin
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 80 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 498 bytes | 124.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/andrew.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/JCSDA-internal/eva.git
 ! [remote rejected] andrew -> andrew (protected branch hook declined)
error: failed to push some refs to 'https://github.com/JCSDA-internal/eva.git'
```

**Comment by CoryMartin-NOAA** [comment]
@ADCollard that is really strange... I wonder if it is because you are not using 'git flow' in the branch name? or something strange like that? Because you were able to push the branch initially...

**Pull request closed without merging**
