### PR TITLE
Add tight layout feature to plotting

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
## Description

Add `tight_layout()` option to plotting routine. Will allow for better spacing/padding between subplots.

### CODE REVIEW

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA tagging you in this as well. Unfortunately I cannot add you as a reviewer still. We will need to address this. Most likely after the holiday.

**Comment by EdwardSafford-NOAA** [comment]
Looks good to me.

**Review by danholdaway — APPROVED** [review]
Could an example be added to one of the tests?

**Comment by CoryMartin-NOAA** [comment]
Ditto what @danholdaway said, @kevindougherty-noaa can you just throw this in one of the test YAMLs (pick one)?

**Comment by CoryMartin-NOAA** [comment]
> @EdwardSafford-NOAA tagging you in this as well. Unfortunately I cannot add you as a reviewer still. We will need to address this. Most likely after the holiday.

@BenjaminRuston is it possible to get @EdwardSafford-NOAA added to this repo to do reviews? or is that a question for @climbfuji ?

**Comment by climbfuji** [comment]
> > @EdwardSafford-NOAA tagging you in this as well. Unfortunately I cannot add you as a reviewer still. We will need to address this. Most likely after the holiday.
> 
> @BenjaminRuston is it possible to get @EdwardSafford-NOAA added to this repo to do reviews? or is that a question for @climbfuji ?

@CoryMartin-NOAA Should I add him to the "eva" team?

**Comment by CoryMartin-NOAA** [comment]
@climbfuji yes please, thanks!

**Comment by climbfuji** [comment]
> @climbfuji yes please, thanks!

Done!

**Comment by CoryMartin-NOAA** [comment]
Thanks @climbfuji ! @EdwardSafford-NOAA you should be able to assign yourself to issues now!

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA Yup, all set.  Thanks!

**Pull request merged**
