### PR TITLE
Fix Level issue 

### LINKED ISSUE #194: [Bug] mon_data_space.py won't load ps data files
## Current behavior (describe the bug)

Legacy DA monitor conventional data files all load and plot except for PS files.  When running the time-series plot `(conTime.yaml`) the xarray.dataset merge operation in `load_dset()` fails with the error `ValueError: dimension 'Level' already exists as a scalar variable`.  

PS files have a Level dimension of 1 which is likely the source of the error.  Some of the monitor data needs to treat 1 as None, and I suspect that's what's erroneously happening here.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Stupidly simple fix, but took _forever_ to find owing to a seriously unhelpful error message.  

This fix enables conventional `ps` type plots to work correctly.  Unlike other conventional time-series data, `ps` has only one level (surface, all others have 13).  With the check on levels > 1 resulted in trying to assign coordinates of None for the dataset's Level dimension.  Adding to the confusion the same error resulted from two different operations (`assign_coordinates()` and then a `merge()` of the date/time values).  The actual error message was `ValueError: dimension 'Level' already exists as a scalar variable`, which really didn't describe the situation _at all_.

Closes #194 .

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA any chance you can fix the unrelated issue that is causing the CI to fail `np.Inf` should be `np.inf`? I may be able to force a merge otherwise (I'm not sure)

**Comment by EdwardSafford-NOAA** [comment]
Having a look now.

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA @EdwardSafford-NOAA This is the exact same issue I just debugged this morning. It is due to the fact that EMCPy's required matplotlib build is outdated. I updated in my PR to the newest version and it solved the CI issues. This may be related to what is happening on WCOSS2 as well and mentioned it to Cory this morning.

**Comment by EdwardSafford-NOAA** [comment]
Yes I spotted that too.  I updated matplotlib to version 3.9.0 (latest afaik) in requirements.txt.  That does not seem to have fixed the CI test though, so maybe there's more I need to do?

**Comment by EdwardSafford-NOAA** [comment]
Oh, I see additional places.  Lemme fix that and retry.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by srherbener** [comment]
Not sure why I'm getting these, but a bunch of emails have come to me with the following message:
```
Branch name bug/level-194 Does not satisfy the Git-Flow naming conventions.
Please rename your local branch, push to GitHub, and delete branch bug/level-194.
Valid branch names begin with feature/ bugfix/ release/ or hotfix/

Repo: eva
Branch: bug/level-194
User: EdwardSafford-NOAA
User email: [62339196+EdwardSafford-NOAA@users.noreply.github.com](mailto:62339196%2BEdwardSafford-NOAA@users.noreply.github.com)
```

Apparently, we've got something watching the repos and trying to enforce git flow naming conventions. I think the watchdog wants the branch to be named `bugfix/level-194` instead of `bug/level-194`. Don't worry about this PR, ie no need to change the branch name. I'm just sending this for future reference.

Thanks!

**Comment by CoryMartin-NOAA** [comment]
Thanks Steve, yeah I'm getting the same automated emails. @EdwardSafford-NOAA just an FYI for future reference

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I think I messed up something in my attempts to fix the CI issue.  It looks like my change to `mon_data_space.py` is no longer in this PR.  That's confusing because the change is in my bug[fix]/level-192 branch on wcoss2, and the branch reports as up to date with my origin/bug[fix]/level-192 branch.  Not quite sure what I'm looking at or how/why my 1 char fix isn't showing up now.

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA I think I may have already merged that into develop, perhaps this branch just needs made up to date with develop?

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA Ok, I think I get it.  You did merge my 1 char change and that is in develop now.  My develop is current, and my bug[fix]/level-192 has develop merged into it.  So everything is copacetic except for the ongoing CI issue.

**Comment by EdwardSafford-NOAA** [comment]
With the level fix now in develop I'm going to close this PR.  The CI error has been resolved by updating the emcpy hash and the matlabplot version.

**Pull request closed without merging**
