### PR TITLE
Update hash for emcpy; fix mapscatter syntax

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

This PR closes issue #77 

@EdwardSafford-NOAA found that there is a syntax issue with EMCpy now if using a more recent version in EVA. This PR bring EVA up to date with EMCpy.

## Dependencies

None

## Impact

Tagging @danholdaway as he may want to use a new EVA tag for SWELL soon...

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA I can't make you a reviewer because I don't have admin privileges and you aren't added to this repo 'officially'. But could you test and report results back here?

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA With these changes `test/testIodaObsSpaceAmsuaN19.yaml` runs to completion.

As you pointed out earlier the change that was made to `map_scatter.py` also needs to be made to `map_gridded.py`.   I may have overlooked it but I haven't found a test case that uses map_gridded.py, so I don't think there is an easy way to test that.

**Review by danholdaway — APPROVED** [review]

**Comment by danholdaway** [comment]
I've merged to get things working again. But I thought we were referring to a specific commit of EMCpy. How could that commit being referenced change and the eva tests have passed in whatever PR did that?

**Comment by CoryMartin-NOAA** [comment]
I am not sure, but I noticed the issue on Orion. Perhaps when you pip install it doesn't update the commit automatically if it already is installed? I think in the CI everything stayed working, but updating local existing installs led to the discrepancy.

**Comment by CoryMartin-NOAA** [comment]
@danholdaway actually seems the more likely scenario is "user error" aka me, I think I installed the update eva first, then installed emcpy, which defaulted to develop in the virtual environment...

**Comment by danholdaway** [comment]
OK. Thanks for the info.

**Pull request merged**
