### PR TITLE
Extend mon_data_space.py to support channel markers

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
## Description

Extend `src/eva/data/mon_data_space.py` to support channel markers.  

If Channel is specified as a dimension in the control file then create three variables in the dataset, `chan_assim`, `chan_nassim`, `chan_yaxis`.  These may be used by the yaml file to plot channel markers.  

The `chan_assim` and `chan_nassim` arrays contain the channel numbers that are assimilated and not assimilated respectively.  Both arrays are padded to 'Channel' length with 0 values, so the yaml file can perform an `accept where` transform to get only those channels that are assimilated and/or not assimilated.  The chan_yaxis provides a constant y axis value of -100 for the channel markers.

Example plot using these changes:

image

## Dependencies
None

## Impact

None

Completes #110

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA @kevindougherty-noaa @ADCollard please have a look when you have a moment.  Thanks.

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA You can set the lower limit of the y-axis to -100 if you would like the channel markers to be on the x-axis instead of floating.

**Comment by EdwardSafford-NOAA** [comment]
Ah so.  That would be done in the yaml file, right?

**Comment by kevindougherty-noaa** [comment]
Yes, I think? Also, the x-axis ticks should be consistent, they are different on each subplot. I believe that can also be adjusted on the yaml? I am not sure what is implemented in eva from emcpy though.

**Comment by EdwardSafford-NOAA** [comment]
I'm looking into the x-axis ticks now and it is not immediately obvious if that's implemented or how it might be if not.  

I see that emcpy's `create_plots.py` has a `set_xticks()` method which takes a list of ticks.   Eva chokes though if I specify `xticks: 1,2,3` in the yaml file.  I'm studying how eva pushes it's configuration info to emcpy now.  But even if this can be made to work it's going to be a bit of a problem.  If there are > 500 channels specifying the xticks list is going to be a pain.  I wish setting an xtick interval was an option.

**Comment by EdwardSafford-NOAA** [comment]
I'm stumped.  I see that in `emcpy/plots/create_plots.py`, `create_figure()` fires `_plot_features()`.  `_plot_features` defines figure_dict which has an entry `'xticks': self._set_xticks` which would seem to map` xticks` to the `_set_xticks` method.  And including this in the yaml works (or rather, runs without error):

` - figure:`
`        xticks: [1,2,3,4,5,6,7,8,9,10,11,12,13,l4,15,16,17,18,19,20,21,22,23,24]`

But the xticks in the resulting plots are not changed.  

Thoughts?  Suggestions?

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA can you try to specify some extreme xtick option like `[1,24]` or `[1,10,20]` just to see if it does anything? My guess is somehow the xticks is being ignored and not overwriting the default. It's not yet clear to me if that is an eva or emcpy issue (guessing the former).

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA My specified xticks option appears in neither of the two plots in the figure.  The upper plot has ticks at 0,5,10,15,20,25 while the lower plot has ticks at 4,6,8,10,12,14,16,18.  The x-axis variable (channel) has values from 1-24.  Not sure why there are two different scales, but neither is what I've asked for.  I have tried fiddling with the values in my xticks specification to no avail. 

I have dumped the figure_conf list and my xticks specification is there.

**Comment by CoryMartin-NOAA** [comment]
Sounds like for whatever reason it's not being passed to emcpy then... strange, @kevindougherty-noaa any thoughts?

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA @CoryMartin-NOAA sorry for the delay, was dealing with some env issues on my end. I just tested out both `set_xticks()` and `set_xticklabels()` using emcpy and both work as expected making me believe this has to be on the eva side of things.

Ed, can you share the plotting section of the yaml here so we can take a look?

**Comment by EdwardSafford-NOAA** [comment]
- figure:
        layout: [2,1]
        figure size: [12,10]
        title: 'ssmis_f18 | Number of Obs Count'
        output name: lineplots/ssmis_f18/summary.ssmis_f18.png
        xticks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,l4,15,16,17,18,19,20,21,22,23,24]

      plots:
        - add_xlabel: 'Channel'
          add_ylabel: 'Observation Count'
          add_legend:
            loc: 'upper right'
          layers:
          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::count_cyc1
            color: 'blue'
            label: '2023062000'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::count_cyc2
            color: 'green'
            label: '2023061918'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::count_cyc3
            color: 'orange'
            label: '2023061912'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::count_cyc4
            color: 'red'
            label: '2023061906'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::assim
            y:
              variable: summary::GsiIeee::chan_yaxis
            color: 'green'
            label: 'Assimilated'
            linestyle: ''
            marker: 's'
            markersize: '6'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::nassim
            y:
              variable: summary::GsiIeee::chan_yaxis
            color: 'red'
            label: 'Non Assimilated'
            linestyle: ''
            marker: 's'
            markersize: '6'

        - add_xlabel: 'Channel'
          add_ylabel: 'Total Bias Correction (K)'
          add_legend:
            loc: 'upper right'
          layers:
          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::total_1cyc
            color: 'blue'
            label: '2023062000'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::total_1d
            color: 'red'
            label: 'Avg last day'

          - type: LinePlot
            x:
              variable: summary::GsiIeee::channel
            y:
              variable: summary::GsiIeee::total_30d
            color: 'green'
            label: 'Avg last 30 days'

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA I believe xticks needs to be in the `plots` subsection, not the `figure` subsection.

**Comment by EdwardSafford-NOAA** [comment]
But if put xticks in plots like this:

      plots:
        - add_xlabel: 'Channel'
          add_ylabel: 'Observation Count'
          add_legend:
            loc: 'upper right'
          xticks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,l4,15,16,17,18,19,20,21,22,23,24]
          layers:

The result is an error:

Traceback (most recent call last):
  File "/home/Edward.Safford/.local/bin/eva", line 8, in <module>
    sys.exit(main())
  File "/home/Edward.Safford/.local/lib/python3.9/site-packages/eva/eva_driver.py", line 88, in main
    eva(config_file)
  File "/home/Edward.Safford/.local/lib/python3.9/site-packages/eva/eva_driver.py", line 64, in eva
    figure_driver(eva_dict, data_collections, timing, logger)
  File "/home/Edward.Safford/.local/lib/python3.9/site-packages/eva/plot_tools/figure_driver.py", line 95, in figure_driver
    make_figure(figure_conf, plots_conf, dynamic_options_conf, data_collections, logger)
  File "/home/Edward.Safford/.local/lib/python3.9/site-packages/eva/plot_tools/figure_driver.py", line 150, in make_figure
    getattr(plotobj, key)(value)
AttributeError: 'CreatePlot' object has no attribute 'xticks'

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA it should be `set_xticks`. https://github.com/NOAA-EMC/emcpy/blob/develop/src/emcpy/plots/create_plots.py#L149C4-L149C4

**Comment by EdwardSafford-NOAA** [comment]
That runs to completion without errors.  Unfortunately hera seems to have a network issue now and I can't mail or scp the file so I can have a look.  Timing is brilliant; mail has worked right up until I might have a working solution. :(  I'll update as soon as can have a look at the image.

**Comment by EdwardSafford-NOAA** [comment]
OK I can confirm it's working as desired.  (Note I only plotted the channel assim/nassim on the first plot.)

image

**Comment by EdwardSafford-NOAA** [comment]
I think it's now safe to declare victory on this.  The channel markers work, as per the image below.  

Note there are unrelated problems with the data.  That's not an eva problem and my plan is to dig into that next.  Also the bias correction plot should have a horizontal line.  I've opened issue #117 to add that capability to eva.

image

**Review by kevindougherty-noaa — APPROVED** [review]
Awesome, looks great to me.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
