### PR TITLE
Fix timestamp depreciation warning (again)

### LINKED ISSUE #201: [Bug] Re-fix the time precision warning in csv_space.py, fix new(?) problem with ps plots
## Current behavior (describe the bug)

I had fixed the time precision warning in `csv_space.py` with #199 but that change is not in develop.  Re-fix that.

I believe there are some other changes I'd made about the same time that are not in develop.  I had stacked up 5 small PRs a couple of weeks ago as we were waiting for the CI test fix so I think some changes got lost on the way.  As I find missing thing I'll add them to this bug report.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Fix timestamp deprecation warning in `csv_data.py`.  This was fixed once but the file change was apparently lost during the confusion with the CI test failures. 

Close #201

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
The documentation build is failing. Not sure if it is related to this PR or something else... Looks like it is failing on something in here:https://github.com/JCSDA-internal/eva-docs/tree/develop/.github/workflows Always something to chase with these GitHub Actions...

**Comment by EdwardSafford-NOAA** [comment]
The EVA documentation dry run failure report is:
```
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```
From what I read on stackoverflow this can be fixed by modifying the conda install in `eva-docs/.github/workflows/docs_dry_run.yaml` to make the install line something along the lines of `conda install --solver=classic conda-forge::conda-libmamba-solver conda-forge::libmamba conda-forge::libmambapy conda-forge::libarchive`.

I'm not sure how to make that change to eva-docs and then test it in eva without first merging it into eva-docs/develop.  Need some help there.

**Comment by CoryMartin-NOAA** [comment]
> I'm not sure how to make that change to eva-docs and then test it in eva without first merging it into eva-docs/develop. Need some help there.
I think that's basically what we have to do @EdwardSafford-NOAA , and revert if we broke something.

**Comment by EdwardSafford-NOAA** [comment]
Ok, I'll create a PR in eva-docs to do this and we'll start a bit of trial and error.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA the documentation test is passing today.  I'm not going to ask any questions; I suggest we declare victory and move swiftly on.

**Review by CoryMartin-NOAA — APPROVED** [review]
🎉

**Pull request merged**
