### PR TITLE
TryToFixCi

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Try to fix the CI failures

### CODE REVIEW

**Comment by danholdaway** [comment]
OK that was easier than I expected it to be. @kevindougherty-noaa this might be what you need to do in EMCpy too if you didn't get to a workaround yet. All comes back to the fact that we can't install a recent version of Cartopy because the GitHub servers use an old proj. Now we have to fix to an old version of matplotlib too so it's compatible with the old version of cartopy.

**Review by kevindougherty-noaa — APPROVED** [review]
Excellent! I'll give it a try on EMCPy as well

**Comment by danholdaway** [comment]
I went ahead and fixed the versions of all packages so we don't experience another break to CI. I'm not sure if this is a good thing to do or not since it likely means the CI environment will become quite different from the environment people will work with in practice. At some point someone will want to use a new feature that isn't available in the CI and then we'll have to revisit all this. I guess some testing is better than no testing. Maybe in the long term we should aim to use the spack-stack container in the action.

**Comment by CoryMartin-NOAA** [comment]
I've used a JCSDA docker container in github actions before for IODA and it was quite straightforward. If they have a spack-stack container available, we should move to that soon.

**Comment by danholdaway** [comment]
Dom is working on a spack-stack container but I don't think it's ready yet.

**Pull request merged**
