### PR TITLE
Add check on control file and graceful exit,

### LINKED ISSUE #191: mon_data_space.py should exit gracefully when requested control file is not found
## Description

`mon_data_space.py` should trap the file not found exception and exit with an error condition (1) when the requested control file is not found.  Without trapping this condition a missing control file will result in an entire model plot job failing.

## Dependencies

None.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Modity `mon_data_space.py` adding a check on the control file and graceful exit if not found.  Without this exit the entire plot job terminates.  With this exit only the affected thread halts (with error message), allowing all other plots to proceed.  

This has been tested on wcoss2 by removing some control files from the test data set.  Missing control files are reported as warnings and all plots with valid control files run to completion.

## Dependencies

None

Resolves #191 .

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
For the CI test failure is it a consensus that we need to bump the emcpy version (now at 9b6756341e)?  And if so to which version?

**Review by kevindougherty-noaa — APPROVED** [review]
Looks good to me.

**Comment by CoryMartin-NOAA** [comment]
> For the CI test failure is it a consensus that we need to bump the emcpy version (now at 9b6756341e)? And if so to which version?

@kevindougherty-noaa do you know the answer to this?

**Comment by kevindougherty-noaa** [comment]
@EdwardSafford-NOAA 

> For the CI test failure is it a consensus that we need to bump the emcpy version (now at 9b6756341e)? And if so to which version?

Good question. I will have new PR for EMCPy next week with some changes needed for the documentation plus some minor changes.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA CI tests have passed so this is good to go now.

**Pull request merged**
