### PR TITLE
feature/latlon-dan -> feature/latlon

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Merge develop and perform a bit of clean up. Map plot looks good for the surface GeoVaLs, thanks for adding this.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Would it be better to just merge this into develop? It should work well enough for now, right? I'm okay with that if you are, keeps the reviews more "agile". Otherwise this is fine too.

**Comment by danholdaway** [comment]
Sure, I'm fine with that. Didn't want to commandeer your efforts in case you had more work in mind but you can always make a new branch. I changed the base

**Comment by CoryMartin-NOAA** [comment]
haven't most of the changes shown here been merged in already? Is this just a github artifact?

**Review by CoryMartin-NOAA — COMMENTED** [review]
Disregard my previous comment, I see the relevant changes only now

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
