### PR TITLE
Allow for flexibility to plot multiple datasets together

### LINKED ISSUE #101: Cannot plot from different datatypes on the same figure
As I understand it the format for the EVA yaml files is as below:

```
diagnostics:
- data:
    type: IodaObsSpace
 
  transforms:

  graphics:

- data:
   type: GsiObsSpace
 
  transforms:

  graphics:
```

I.e., the type, transforms and graphics are all under the `data` header and so you cannot have a figure produced that includes data from both `IodaObsSpace` and `GsiObsSpace`

This is something that would be desirable.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

Currently EVA links datasets and figures together, but that means that you can't plot say FV3 backgrounds with obs from IODA overlaid. This PR decouples the diagnostics and allows for multiple types of datasets to be read in for each diagnostic.

Closes #101 

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@danholdaway @asewnath this is a draft for now. I think I made the right change for the Jupyter test, but please check. And please let me know if you think this is a suitable approach to take, @danholdaway, or if you have a better suggestion. This was my quick and dirty suggestion.

**Comment by danholdaway** [comment]
Thanks for working on this @CoryMartin-NOAA. I think it's a good idea and actually how I thought it already worked so it's good to make it actually work like that! Probably a little to do to get the tests passing. If you need help with the interactive mode let us know. Would it be possible to add another test that plots the cube sphere restarts with some observational data?

**Comment by CoryMartin-NOAA** [comment]
@danholdaway good idea, let me add a test like that while I fix the coding norms/notebook test.

**Comment by CoryMartin-NOAA** [comment]
@danholdaway @asewnath I do think I'll need help with debugging the Notebook tests. Ugh, this is also failing now if I re-run an old PR's test, so something changed in the GitHub runner... again...

**Comment by CoryMartin-NOAA** [comment]
Screenshot 2023-05-18 at 1 27 37 PM
aircraft dots plotted over T2m

**Comment by CoryMartin-NOAA** [comment]
@danholdaway @asewnath notebook tests fixed by updating bokeh and python version, please make sure that's okay with you

**Comment by danholdaway** [comment]
Thanks for fixing the CI for the notebooks @CoryMartin-NOAA. One minor thing: this probably warrants a change to the minor version since it's actually quite a significant feature update (even thought we thought it was already part of the system). Can we go to 1.4.0 in the setup.py file? Then we can tag as soon as this gets merged.

**Comment by CoryMartin-NOAA** [comment]
@danholdaway done

**Review by danholdaway — APPROVED** [review]

**Review by danholdaway — APPROVED** [review]

**Pull request merged**
